sudo: false
language: node_js
node_js: node
cache: yarn

notifications:
  slack:
    rooms:
      - castilh0s:$SLACK_TOKEN#toplast
    on_success: always
    on_failure: always

script:
  - yarn test:unit
env:
  - CI=true

# before_deploy:
#   - yarn global add netlify-cli
#   - yarn build

# deploy:
#   provider: script
#   script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./dist
#   skip_cleanup: true
#   on:
#     branch: master
